services:
  gateway:
    command: "/usr/libexec/ipsec/charon"
    build:
      dockerfile: ./docker/gateway/Dockerfile
      context: .
      args:
        python_version: "${DOCKER_PYTHON_VERSION:?}"
        strongswan_version: "${DOCKER_STRONGSWAN_VERSION:?}"
    privileged: true

  roadwarrior:
    extends: gateway
    build:
      dockerfile: ./docker/roadwarrior/Dockerfile
      args:
        python_version: "${DOCKER_PYTHON_VERSION:?}"
        strongswan_version: "${DOCKER_STRONGSWAN_VERSION:?}"
    links:
     - "gateway"
