# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeerAuthentication',
            new_name='Authentication',
        ),
    ]
