# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_auto_20160321_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='connection',
        ),
        migrations.AddField(
            model_name='authentication',
            name='local',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local', to='connections.Connection'),
        ),
        migrations.AddField(
            model_name='authentication',
            name='remote',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote', to='connections.Connection'),
        ),
    ]
